#!/usr/bin/env python3
"""
Create Google Sheets project tracker for Milestone Group - HubSpot CRM Implementation.
Generated by /project-sheet for Milestone Group.

Usage:
    python3 create_project_sheet.py "Milestone Group" --dry-run
    python3 create_project_sheet.py "Milestone Group"
    python3 create_project_sheet.py "Milestone Group" --refresh
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------

def check_dependencies() -> None:
    """Verify required packages are installed."""
    missing = []  # type: List[str]
    try:
        import gspread  # noqa: F401
    except ImportError:
        missing.append("gspread")
    try:
        from google.oauth2.service_account import Credentials  # noqa: F401
    except ImportError:
        missing.append("google-auth")
    if missing:
        print(f"Missing packages: {', '.join(missing)}")
        print(f"Install with: pip3 install {' '.join(missing)}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------

def get_credential(service_name: str) -> str:
    """Retrieve credential from macOS Keychain."""
    try:
        result = subprocess.check_output(
            ["security", "find-generic-password",
             "-a", "harbuckconsulting",
             "-s", service_name,
             "-w"],
            stderr=subprocess.DEVNULL
        )
        return result.decode("utf-8").strip()
    except subprocess.CalledProcessError:
        print(f"ERROR: Could not retrieve {service_name} from Keychain.")
        print(f"Add it with: security add-generic-password "
              f"-a harbuckconsulting -s {service_name} -w '<value>'")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Delivery state
# ---------------------------------------------------------------------------

def load_delivery_state(client_dir: str) -> Dict[str, Any]:
    state_path = os.path.join(client_dir, "delivery-state.json")
    if os.path.exists(state_path):
        with open(state_path, "r") as f:
            return json.load(f)
    return {}


def save_delivery_state(client_dir: str, updates: Dict[str, Any]) -> None:
    state = load_delivery_state(client_dir)
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(state.get(key), dict):
            state[key].update(value)
        else:
            state[key] = value
    state["lastUpdated"] = datetime.now(timezone.utc).isoformat()
    state_path = os.path.join(client_dir, "delivery-state.json")
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)
    print(f"Updated {state_path}")


def plan_hash(plan_path: str) -> str:
    with open(plan_path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------

def build_summary_tab(ws: Any, plan: Dict[str, Any]) -> None:
    """Build the Summary tab."""
    import gspread
    from gspread.utils import rowcol_to_a1

    client = plan["client"]
    eng = plan["engagement"]

    # Header block
    header_data = [
        ["Client", client["name"]],
        ["Engagement", eng["name"]],
        ["Start Date", eng["startDate"]],
        ["End Date", eng["estimatedEndDate"]],
        ["Total Hours", f"{eng['totalHours']['min']}-{eng['totalHours']['max']} (median {eng['totalHours']['median']})"],
        ["Pricing", f"{eng['pricing']['model'].title()} - ${eng['pricing']['amount']:,}"],
        ["Payment Terms", eng["pricing"]["paymentTerms"]],
        [],
    ]

    # Phase table header
    phase_header = ["Phase", "Start Date", "End Date", "Hours (Min)", "Hours (Max)", "Hours (Median)", "Status"]
    header_data.append(phase_header)

    total_min = 0
    total_max = 0
    total_med = 0

    for phase in plan["phases"]:
        p_min = sum(w["hours"]["min"] for w in phase["workstreams"])
        p_max = sum(w["hours"]["max"] for w in phase["workstreams"])
        p_med = sum(w["hours"]["median"] for w in phase["workstreams"])
        total_min += p_min
        total_max += p_max
        total_med += p_med
        header_data.append([
            f"Phase {phase['order']}: {phase['name']}",
            phase["startDate"],
            phase["endDate"],
            p_min, p_max, p_med,
            "Not Started"
        ])

    # Cross-phase
    for cw in plan.get("crossPhaseWorkstreams", []):
        total_min += cw["hours"]["min"]
        total_max += cw["hours"]["max"]
        total_med += cw["hours"]["median"]
        header_data.append([
            cw["name"],
            eng["startDate"],
            eng["estimatedEndDate"],
            cw["hours"]["min"], cw["hours"]["max"], cw["hours"]["median"],
            "Ongoing"
        ])

    # Totals
    header_data.append(["TOTAL", "", "", total_min, total_max, total_med, ""])

    header_data.append([])
    header_data.append(["ASSUMPTIONS"])
    for a in plan.get("assumptions", []):
        header_data.append([f"  - {a}"])

    header_data.append([])
    header_data.append(["EXCLUSIONS"])
    for e in plan.get("exclusions", []):
        header_data.append([f"  - {e}"])

    ws.update(header_data, "A1")

    # Formatting
    phase_header_row = 9  # Row where phase table starts
    ws.format(f"A1:B7", {
        "textFormat": {"bold": True},
    })
    ws.format(f"A{phase_header_row}:G{phase_header_row}", {
        "backgroundColor": {"red": 0.1, "green": 0.14, "blue": 0.49},
        "textFormat": {"bold": True, "foregroundColor": {"red": 1, "green": 1, "blue": 1}},
    })
    ws.freeze(rows=phase_header_row)


def build_phase_detail_tab(ws: Any, phase: Dict[str, Any]) -> None:
    """Build a phase detail tab."""
    # Header
    header = ["Workstream ID", "Workstream Name", "Tasks", "Hours (Min)", "Hours (Max)", "Hours (Median)", "Owner", "Status"]
    rows = [header]

    for workstream in phase["workstreams"]:
        tasks_text = "\n".join(f"{i+1}. {t}" for i, t in enumerate(workstream["tasks"]))
        rows.append([
            workstream["id"],
            workstream["name"],
            tasks_text,
            workstream["hours"]["min"],
            workstream["hours"]["max"],
            workstream["hours"]["median"],
            workstream["owner"],
            "Not Started",
        ])

    # Totals
    t_min = sum(w["hours"]["min"] for w in phase["workstreams"])
    t_max = sum(w["hours"]["max"] for w in phase["workstreams"])
    t_med = sum(w["hours"]["median"] for w in phase["workstreams"])
    rows.append(["", "TOTAL", "", t_min, t_max, t_med, "", ""])

    rows.append([])
    rows.append(["SUCCESS CRITERIA"])
    for sc in phase.get("successCriteria", []):
        rows.append([f"  - {sc}"])

    ws.update(rows, "A1")

    # Formatting
    ws.format("A1:H1", {
        "backgroundColor": {"red": 0.1, "green": 0.14, "blue": 0.49},
        "textFormat": {"bold": True, "foregroundColor": {"red": 1, "green": 1, "blue": 1}},
    })
    ws.freeze(rows=1)


def build_risk_tab(ws: Any, plan: Dict[str, Any]) -> None:
    """Build the Risk Register tab."""
    header = ["Risk ID", "Risk Name", "Severity", "Likelihood", "Impact", "Mitigation", "Owner"]
    rows = [header]

    for risk in plan.get("risks", []):
        rows.append([
            risk["id"],
            risk["name"],
            risk["severity"].title(),
            risk["likelihood"].title(),
            risk["impact"],
            risk["mitigation"],
            risk["owner"],
        ])

    rows.append([])
    rows.append(["CLIENT RESPONSIBILITIES"])
    for cr in plan.get("clientResponsibilities", []):
        rows.append([f"  - {cr}"])

    ws.update(rows, "A1")

    # Header formatting
    ws.format("A1:G1", {
        "backgroundColor": {"red": 0.1, "green": 0.14, "blue": 0.49},
        "textFormat": {"bold": True, "foregroundColor": {"red": 1, "green": 1, "blue": 1}},
    })
    ws.freeze(rows=1)

    # Conditional formatting for severity
    from gspread_formatting import ConditionalFormatRule, BooleanCondition, CellFormat, Color, get_conditional_format_rules, set_frozen_column_count
    # Note: gspread_formatting may not be installed; use basic approach instead
    # We'll apply severity colors via batch format calls
    for i, risk in enumerate(plan.get("risks", []), start=2):
        severity = risk["severity"]
        if severity == "high":
            color = {"red": 0.91, "green": 0.46, "blue": 0.47}
        elif severity == "medium":
            color = {"red": 0.98, "green": 0.91, "blue": 0.53}
        else:
            color = {"red": 0.58, "green": 0.84, "blue": 0.58}
        ws.format(f"C{i}", {"backgroundColor": color})


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create Google Sheets project tracker from plan.json"
    )
    parser.add_argument("client_dir",
                        help="Path to client folder containing plan.json")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print planned actions without executing")
    parser.add_argument("--detail", action="store_true", default=True,
                        help="Generate all tabs (default)")
    parser.add_argument("--summary-only", action="store_true",
                        help="Generate only the Summary tab")
    parser.add_argument("--refresh", action="store_true",
                        help="Update existing sheet instead of creating new")
    parser.add_argument("--force", action="store_true",
                        help="Create new sheet even if one exists")
    args = parser.parse_args()

    client_dir = args.client_dir
    dry_run = args.dry_run

    # Load plan
    plan_path = os.path.join(client_dir, "plan.json")
    if not os.path.exists(plan_path):
        print(f"ERROR: {plan_path} not found")
        sys.exit(1)
    with open(plan_path, "r") as f:
        plan = json.load(f)

    client_name = plan["client"]["name"]
    engagement_name = plan["engagement"]["name"]
    sheet_title = f"{client_name} - {engagement_name} Tracker"

    # Idempotency check
    state = load_delivery_state(client_dir)
    existing_sheet = state.get("googleSheet", {}).get("sheetId")

    if existing_sheet and not args.force and not args.refresh:
        url = state["googleSheet"].get("sheetUrl", "unknown")
        print(f"Google Sheet already exists: {url}")
        print("Use --refresh to update or --force to create new.")
        sys.exit(0)

    # Determine tabs
    phases = plan["phases"]
    tab_names = ["Summary"]
    if not args.summary_only:
        for p in phases:
            tab_name = f"Phase {p['order']}: {p['name']}"
            # Sheets tab names max 100 chars
            if len(tab_name) > 100:
                tab_name = tab_name[:97] + "..."
            tab_names.append(tab_name)
        tab_names.append("Risk Register")

    prefix = "[DRY RUN] " if dry_run else ""

    print(f"\n{'='*60}")
    print(f"{prefix}GOOGLE SHEET: {sheet_title}")
    print(f"{'='*60}")
    print(f"Tabs: {len(tab_names)}")
    for t in tab_names:
        print(f"  - {t}")
    print(f"Share with: {plan['client']['contactEmail']}")
    if args.refresh and existing_sheet:
        print(f"Mode: Refresh existing ({existing_sheet})")
    else:
        print("Mode: Create new")
    print()

    if dry_run:
        # Print tab content preview
        print(f"{prefix}Summary tab:")
        print(f"  Header: client info, engagement details")
        print(f"  Phase table: {len(phases)} phases + cross-phase + totals")
        print(f"  Assumptions: {len(plan.get('assumptions', []))} items")
        print(f"  Exclusions: {len(plan.get('exclusions', []))} items")

        if not args.summary_only:
            for p in phases:
                ws_count = len(p["workstreams"])
                task_count = sum(len(w["tasks"]) for w in p["workstreams"])
                sc_count = len(p.get("successCriteria", []))
                print(f"\n{prefix}Phase {p['order']} detail tab:")
                print(f"  Workstreams: {ws_count}")
                print(f"  Tasks: {task_count}")
                print(f"  Success criteria: {sc_count}")

            print(f"\n{prefix}Risk Register tab:")
            print(f"  Risks: {len(plan.get('risks', []))}")
            print(f"  Client responsibilities: {len(plan.get('clientResponsibilities', []))}")

        print(f"\n{prefix}No changes made. Run without --dry-run to execute.")
        return

    # Real execution
    check_dependencies()

    import gspread
    from google.oauth2.service_account import Credentials

    sa_json = get_credential("GOOGLE_SERVICE_ACCOUNT_JSON")
    sa_info = json.loads(sa_json)
    scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ]
    credentials = Credentials.from_service_account_info(sa_info, scopes=scopes)
    gc = gspread.authorize(credentials)

    if args.refresh and existing_sheet:
        print(f"Opening existing sheet: {existing_sheet}")
        spreadsheet = gc.open_by_key(existing_sheet)
    else:
        print(f"Creating sheet: {sheet_title}")
        spreadsheet = gc.create(sheet_title)

    # Create/get tabs
    existing_tabs = [ws.title for ws in spreadsheet.worksheets()]

    # Summary tab (rename Sheet1 if present)
    if "Sheet1" in existing_tabs:
        summary_ws = spreadsheet.worksheet("Sheet1")
        summary_ws.update_title("Summary")
    elif "Summary" in existing_tabs:
        summary_ws = spreadsheet.worksheet("Summary")
        summary_ws.clear()
    else:
        summary_ws = spreadsheet.add_worksheet("Summary", rows=100, cols=10)

    build_summary_tab(summary_ws, plan)
    print("  Built: Summary")

    if not args.summary_only:
        for p in phases:
            tab_name = f"Phase {p['order']}: {p['name']}"
            if len(tab_name) > 100:
                tab_name = tab_name[:97] + "..."
            if tab_name in existing_tabs:
                phase_ws = spreadsheet.worksheet(tab_name)
                phase_ws.clear()
            else:
                phase_ws = spreadsheet.add_worksheet(tab_name, rows=50, cols=10)
            build_phase_detail_tab(phase_ws, p)
            print(f"  Built: {tab_name}")

        # Risk Register
        if "Risk Register" in existing_tabs:
            risk_ws = spreadsheet.worksheet("Risk Register")
            risk_ws.clear()
        else:
            risk_ws = spreadsheet.add_worksheet("Risk Register", rows=50, cols=10)
        build_risk_tab(risk_ws, plan)
        print("  Built: Risk Register")

    # Share with client
    contact_email = plan["client"]["contactEmail"]
    try:
        spreadsheet.share(contact_email, perm_type="user", role="reader")
        print(f"  Shared with: {contact_email}")
    except Exception as e:
        print(f"  WARNING: Could not share with {contact_email}: {e}")

    sheet_url = spreadsheet.url
    print(f"\nSheet URL: {sheet_url}")

    # Save delivery state
    save_delivery_state(client_dir, {
        "clientName": client_name,
        "planJsonHash": plan_hash(plan_path),
        "googleSheet": {
            "sheetId": spreadsheet.id,
            "sheetUrl": sheet_url,
            "sharedWith": [contact_email],
            "createdAt": datetime.now(timezone.utc).isoformat() if not args.refresh else state.get("googleSheet", {}).get("createdAt", ""),
            "lastRefreshed": datetime.now(timezone.utc).isoformat() if args.refresh else None,
        },
    })


if __name__ == "__main__":
    main()
