#!/usr/bin/env python3
"""
Create Linear project for Milestone Group - HubSpot CRM Implementation.
Generated by /project-plan for Milestone Group.

Usage:
    python3 create_linear_project.py "Milestone Group" --dry-run
    python3 create_linear_project.py "Milestone Group"
    python3 create_linear_project.py "Milestone Group" --team SAYER
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------

def get_credential(service_name: str) -> str:
    """Retrieve credential from macOS Keychain."""
    try:
        result = subprocess.check_output(
            ["security", "find-generic-password",
             "-a", "harbuckconsulting",
             "-s", service_name,
             "-w"],
            stderr=subprocess.DEVNULL
        )
        return result.decode("utf-8").strip()
    except subprocess.CalledProcessError:
        print(f"ERROR: Could not retrieve {service_name} from Keychain.")
        print(f"Add it with: security add-generic-password "
              f"-a harbuckconsulting -s {service_name} -w '<value>'")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Linear GraphQL helpers
# ---------------------------------------------------------------------------

def linear_request(
    query: str,
    variables: Optional[Dict[str, Any]] = None,
    api_key: str = "",
    dry_run: bool = False
) -> Dict[str, Any]:
    """Execute a Linear GraphQL request."""
    if dry_run:
        return {"data": {}}

    payload = json.dumps({
        "query": query,
        "variables": variables or {}
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.linear.app/graphql",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": api_key,
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            if "errors" in result:
                print(f"Linear API error: {json.dumps(result['errors'], indent=2)}")
                sys.exit(1)
            return result
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8") if e.fp else ""
        print(f"Linear API HTTP {e.code}: {body}")
        sys.exit(1)


def get_team(api_key: str, team_key: Optional[str], dry_run: bool) -> Tuple[str, str]:
    """Return (team_id, team_key). Auto-discovers first team if key not given."""
    if dry_run:
        return ("team-dry-run-id", team_key or "SAYER")

    query = "{ teams { nodes { id key name } } }"
    result = linear_request(query, api_key=api_key)
    teams = result.get("data", {}).get("teams", {}).get("nodes", [])
    if not teams:
        print("ERROR: No teams found in Linear workspace.")
        sys.exit(1)

    if team_key:
        for t in teams:
            if t["key"] == team_key:
                return (t["id"], t["key"])
        print(f"ERROR: Team '{team_key}' not found. Available: "
              f"{', '.join(t['key'] for t in teams)}")
        sys.exit(1)

    chosen = teams[0]
    print(f"Auto-selected team: {chosen['name']} ({chosen['key']})")
    return (chosen["id"], chosen["key"])


def get_or_create_label(
    api_key: str, team_id: str, name: str, color: Optional[str],
    existing_labels: Dict[str, str], dry_run: bool
) -> str:
    """Return label ID, creating if needed."""
    if name in existing_labels:
        return existing_labels[name]

    if dry_run:
        label_id = f"label-dry-run-{name}"
        existing_labels[name] = label_id
        return label_id

    mutation = """
    mutation CreateLabel($input: IssueLabelCreateInput!) {
        issueLabelCreate(input: $input) {
            issueLabel { id name }
            success
        }
    }
    """
    variables = {
        "input": {
            "teamId": team_id,
            "name": name,
        }
    }  # type: Dict[str, Any]
    if color:
        variables["input"]["color"] = color

    result = linear_request(mutation, variables, api_key=api_key)
    label_data = result.get("data", {}).get("issueLabelCreate", {})
    if not label_data.get("success"):
        print(f"WARNING: Could not create label '{name}'. Continuing without it.")
        return ""
    label_id = label_data["issueLabel"]["id"]
    existing_labels[name] = label_id
    return label_id


def fetch_existing_labels(api_key: str, team_id: str, dry_run: bool) -> Dict[str, str]:
    """Fetch all existing labels for the team. Returns {name: id}."""
    if dry_run:
        return {}
    query = """
    query($teamId: ID!) {
        issueLabels(filter: { team: { id: { eq: $teamId } } }) {
            nodes { id name }
        }
    }
    """
    result = linear_request(query, {"teamId": team_id}, api_key=api_key)
    labels = result.get("data", {}).get("issueLabels", {}).get("nodes", [])
    return {l["name"]: l["id"] for l in labels}


def create_project(
    api_key: str, team_id: str, name: str, description: str,
    start_date: str, target_date: str, dry_run: bool
) -> str:
    """Create a Linear project. Returns project ID."""
    if dry_run:
        return "project-dry-run-id"

    mutation = """
    mutation CreateProject($input: ProjectCreateInput!) {
        projectCreate(input: $input) {
            project { id url slugId }
            success
        }
    }
    """
    variables = {
        "input": {
            "name": name,
            "description": description,
            "teamIds": [team_id],
            "startDate": start_date,
            "targetDate": target_date,
        }
    }
    result = linear_request(mutation, variables, api_key=api_key)
    project_data = result.get("data", {}).get("projectCreate", {})
    if not project_data.get("success"):
        print("ERROR: Failed to create project.")
        sys.exit(1)
    return project_data["project"]["id"]


def get_project_url(api_key: str, project_id: str, dry_run: bool) -> str:
    """Get the project URL."""
    if dry_run:
        return "https://linear.app/harbuck/project/milestone-dry-run"
    query = """
    query($id: String!) {
        project(id: $id) { url }
    }
    """
    result = linear_request(query, {"id": project_id}, api_key=api_key)
    return result.get("data", {}).get("project", {}).get("url", "")


def create_issue(
    api_key: str, team_id: str, title: str, description: str,
    label_ids: List[str], project_id: str,
    parent_id: Optional[str], dry_run: bool
) -> str:
    """Create a Linear issue. Returns issue ID."""
    if dry_run:
        return f"issue-dry-run-{title[:20]}"

    mutation = """
    mutation CreateIssue($input: IssueCreateInput!) {
        issueCreate(input: $input) {
            issue { id identifier url }
            success
        }
    }
    """
    input_data = {
        "teamId": team_id,
        "title": title,
        "description": description,
        "projectId": project_id,
        "labelIds": [lid for lid in label_ids if lid],
    }  # type: Dict[str, Any]
    if parent_id:
        input_data["parentId"] = parent_id

    result = linear_request(mutation, {"input": input_data}, api_key=api_key)
    issue_data = result.get("data", {}).get("issueCreate", {})
    if not issue_data.get("success"):
        print(f"WARNING: Failed to create issue '{title}'.")
        return ""
    return issue_data["issue"]["id"]


# ---------------------------------------------------------------------------
# Delivery state
# ---------------------------------------------------------------------------

def load_delivery_state(client_dir: str) -> Dict[str, Any]:
    """Load existing delivery-state.json or return empty dict."""
    state_path = os.path.join(client_dir, "delivery-state.json")
    if os.path.exists(state_path):
        with open(state_path, "r") as f:
            return json.load(f)
    return {}


def save_delivery_state(client_dir: str, updates: Dict[str, Any]) -> None:
    """Merge updates into delivery-state.json."""
    state = load_delivery_state(client_dir)
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(state.get(key), dict):
            state[key].update(value)
        else:
            state[key] = value
    state["lastUpdated"] = datetime.now(timezone.utc).isoformat()
    state_path = os.path.join(client_dir, "delivery-state.json")
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)
    print(f"Updated {state_path}")


def plan_hash(plan_path: str) -> str:
    """SHA-256 hash of plan.json for drift detection."""
    with open(plan_path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# Label color map
PHASE_COLORS = {
    "phase-1": "#4186e0",
    "phase-2": "#0f783c",
    "phase-3": "#e06641",
}
PREFIX_COLORS = {
    "CRM": "#4186e0",
    "MIG": "#e8a441",
    "INT": "#0f783c",
    "TRN": "#9b59b6",
    "UAT": "#e06641",
    "DOC": "#95a5a6",
    "PM": "#34495e",
}
OWNER_COLORS = {
    "sayer": "#1abc9c",
    "client": "#e74c3c",
    "shared": "#f39c12",
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create Linear project from plan.json"
    )
    parser.add_argument("client_dir",
                        help="Path to client folder containing plan.json")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print planned actions without executing")
    parser.add_argument("--team", default=None,
                        help="Linear team key (auto-discovers if not set)")
    parser.add_argument("--force", action="store_true",
                        help="Re-create even if delivery-state.json has existing IDs")
    args = parser.parse_args()

    client_dir = args.client_dir
    dry_run = args.dry_run

    # Load plan
    plan_path = os.path.join(client_dir, "plan.json")
    if not os.path.exists(plan_path):
        print(f"ERROR: {plan_path} not found")
        sys.exit(1)
    with open(plan_path, "r") as f:
        plan = json.load(f)

    # Idempotency check
    state = load_delivery_state(client_dir)
    if state.get("linear", {}).get("projectId") and not args.force:
        project_url = state["linear"].get("projectUrl", "unknown")
        print(f"Linear project already exists: {project_url}")
        print("Use --force to re-create.")
        sys.exit(0)

    # Extract plan data
    client_name = plan["client"]["name"]
    engagement = plan["engagement"]
    project_name = f"{client_name} - {engagement['name']}"
    phases = plan["phases"]
    cross_phase = plan.get("crossPhaseWorkstreams", [])

    description = (
        f"**Scope Source:** {engagement['scopeSource']}\n"
        f"**Timeline:** {engagement['startDate']} to {engagement['estimatedEndDate']}\n"
        f"**Hours:** {engagement['totalHours']['min']}-"
        f"{engagement['totalHours']['max']} "
        f"(median {engagement['totalHours']['median']})\n"
        f"**Pricing:** {engagement['pricing']['model']} - "
        f"${engagement['pricing']['amount']:,}\n"
        f"**Payment:** {engagement['pricing']['paymentTerms']}"
    )

    # Count items for summary
    total_workstreams = sum(len(p["workstreams"]) for p in phases) + len(cross_phase)
    total_tasks = sum(
        len(ws["tasks"]) for p in phases for ws in p["workstreams"]
    )

    prefix = "[DRY RUN] " if dry_run else ""

    print(f"\n{'='*60}")
    print(f"{prefix}LINEAR PROJECT: {project_name}")
    print(f"{'='*60}")
    print(f"Phases: {len(phases)}")
    print(f"Workstreams: {total_workstreams}")
    print(f"Tasks (sub-issues): {total_tasks}")
    print(f"Timeline: {engagement['startDate']} -> {engagement['estimatedEndDate']}")
    print()

    # Get API key
    if not dry_run:
        api_key = get_credential("LINEAR_API_KEY")
    else:
        api_key = "dry-run-key"

    # Get team
    team_id, team_key = get_team(api_key, args.team, dry_run)
    print(f"{prefix}Team: {team_key} ({team_id})")

    # Fetch existing labels
    existing_labels = fetch_existing_labels(api_key, team_id, dry_run)

    # Create labels
    print(f"\n{prefix}Creating labels...")
    label_map = {}  # type: Dict[str, str]

    for phase in phases:
        phase_label_name = f"Phase {phase['order']}: {phase['name']}"
        color = PHASE_COLORS.get(phase["id"])
        lid = get_or_create_label(
            api_key, team_id, phase_label_name, color, existing_labels, dry_run
        )
        label_map[phase["id"]] = lid
        print(f"  {prefix}Label: {phase_label_name}")

    # Cross-phase label
    cross_lid = get_or_create_label(
        api_key, team_id, "Cross-Phase", "#34495e", existing_labels, dry_run
    )
    label_map["cross-phase"] = cross_lid
    print(f"  {prefix}Label: Cross-Phase")

    # Prefix labels
    prefixes_seen = set()  # type: set
    for phase in phases:
        for ws in phase["workstreams"]:
            prefix_str = ws["id"].split("-")[0]
            prefixes_seen.add(prefix_str)
    for cw in cross_phase:
        prefix_str = cw["id"].split("-")[0]
        prefixes_seen.add(prefix_str)

    for pfx in sorted(prefixes_seen):
        color = PREFIX_COLORS.get(pfx)
        lid = get_or_create_label(
            api_key, team_id, pfx, color, existing_labels, dry_run
        )
        label_map[f"prefix-{pfx}"] = lid
        print(f"  {prefix}Label: {pfx}")

    # Owner labels
    for owner in ["sayer", "client", "shared"]:
        color = OWNER_COLORS.get(owner)
        lid = get_or_create_label(
            api_key, team_id, owner, color, existing_labels, dry_run
        )
        label_map[f"owner-{owner}"] = lid
        print(f"  {prefix}Label: {owner}")

    # Create project
    print(f"\n{prefix}Creating project: {project_name}")
    project_id = create_project(
        api_key, team_id, project_name, description,
        engagement["startDate"], engagement["estimatedEndDate"], dry_run
    )
    project_url = get_project_url(api_key, project_id, dry_run)
    print(f"  {prefix}Project ID: {project_id}")
    print(f"  {prefix}URL: {project_url}")

    # Create issues
    issue_map = {}  # type: Dict[str, str]

    for phase in phases:
        phase_label_id = label_map.get(phase["id"], "")
        print(f"\n{prefix}Phase {phase['order']}: {phase['name']}")

        for ws in phase["workstreams"]:
            ws_prefix = ws["id"].split("-")[0]
            ws_label_ids = [
                phase_label_id,
                label_map.get(f"prefix-{ws_prefix}", ""),
                label_map.get(f"owner-{ws['owner']}", ""),
            ]

            ws_desc = (
                f"**Workstream:** {ws['id']} - {ws['name']}\n"
                f"**Phase:** {phase['name']}\n"
                f"**Hours:** {ws['hours']['min']}-{ws['hours']['max']} "
                f"(median {ws['hours']['median']})\n"
                f"**Owner:** {ws['owner']}\n\n"
                f"**Tasks:**\n" +
                "\n".join(f"- [ ] {t}" for t in ws["tasks"])
            )

            ws_title = f"[{ws['id']}] {ws['name']}"
            print(f"  {prefix}Issue: {ws_title}")

            ws_issue_id = create_issue(
                api_key, team_id, ws_title, ws_desc,
                ws_label_ids, project_id, None, dry_run
            )
            issue_map[ws["id"]] = ws_issue_id

            # Sub-issues for tasks
            for task in ws["tasks"]:
                print(f"    {prefix}Sub-issue: {task[:60]}")
                create_issue(
                    api_key, team_id, task, "",
                    ws_label_ids, project_id, ws_issue_id, dry_run
                )

    # Cross-phase workstreams
    if cross_phase:
        cross_label_id = label_map.get("cross-phase", "")
        print(f"\n{prefix}Cross-Phase Workstreams")
        for cw in cross_phase:
            cw_prefix = cw["id"].split("-")[0]
            cw_label_ids = [
                cross_label_id,
                label_map.get(f"prefix-{cw_prefix}", ""),
                label_map.get(f"owner-{cw['owner']}", ""),
            ]
            cw_desc = (
                f"**Workstream:** {cw['id']} - {cw['name']}\n"
                f"**Hours:** {cw['hours']['min']}-{cw['hours']['max']} "
                f"(median {cw['hours']['median']})\n"
                f"**Owner:** {cw['owner']}\n"
                f"**Cadence:** {cw.get('cadence', 'N/A')}"
            )
            cw_title = f"[{cw['id']}] {cw['name']}"
            print(f"  {prefix}Issue: {cw_title}")
            cw_issue_id = create_issue(
                api_key, team_id, cw_title, cw_desc,
                cw_label_ids, project_id, None, dry_run
            )
            issue_map[cw["id"]] = cw_issue_id

    # Summary
    print(f"\n{'='*60}")
    print(f"{prefix}SUMMARY")
    print(f"{'='*60}")
    print(f"Project: {project_name}")
    print(f"URL: {project_url}")
    print(f"Labels created: {len(label_map)}")
    print(f"Workstream issues: {len(issue_map)}")
    print(f"Task sub-issues: {total_tasks}")
    print()

    # Save delivery state (skip on dry-run)
    if not dry_run:
        save_delivery_state(client_dir, {
            "clientName": client_name,
            "planJsonHash": plan_hash(plan_path),
            "linear": {
                "projectId": project_id,
                "projectUrl": project_url,
                "teamId": team_id,
                "issueMap": issue_map,
                "labelMap": label_map,
                "createdAt": datetime.now(timezone.utc).isoformat(),
            },
        })
        print("Delivery state saved.")
    else:
        print("[DRY RUN] No changes made. Run without --dry-run to execute.")


if __name__ == "__main__":
    main()
